[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

# Redirects для поддомена admin
[[redirects]]
  from = "https://admin.chefupkz.netlify.app/*"
  to = "/dashboard/moderate/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://admin.chefupkz.netlify.app"
  to = "/dashboard/moderate/jobs"
  status = 200
  force = true
